import json
import re
from config import GROQ_API_KEY, PAGEINDEX_API_KEY
from typing import Optional


def generate_cards_with_pageindex(json_path: str, subject: str = "general") -> list[dict]:
    """
    Generate flashcards using the structure generated by the LOCAL PageIndex clone.
    Traverses the JSON tree to generate cards for each significant node.
    """
    import json
    with open(json_path, "r", encoding="utf-8") as f:
        structure = json.load(f)

    # Helper function to get text from all nodes in the tree
    def extract_node_texts(nodes, result_list):
        if isinstance(nodes, list):
            for node in nodes:
                extract_node_texts(node, result_list)
        elif isinstance(nodes, dict):
            # Only use nodes with substantial text
            text = nodes.get("text", "")
            if len(text.split()) > 100:
                result_list.append(text)
            
            if "nodes" in nodes:
                extract_node_texts(nodes["nodes"], result_list)

    all_texts = []
    extract_node_texts(structure, all_texts)

    # If the tree is empty or too small, fall back to extracting text from the file (handled in route)
    if not all_texts:
        return []

    # Generate cards for each extracted text block
    all_cards = []
    # Limit to top 10 sections to avoid huge costs/time unless it's a massive doc
    for text in all_texts[:10]:
        cards = generate_cards_from_text(text, subject=subject)
        all_cards.extend(cards)

    return all_cards

SUBJECT_PROMPTS = {
    "history": """You are an expert history educator creating flashcards for CBSE Class 10 students.

CRITICAL RULES:
1. Each card must be COMPLETE and SELF-CONTAINED
2. Questions must be CLEAR and SPECIFIC
3. Answers must be CONCISE (2-4 sentences max)
4. NO incomplete sentences or fragments
5. NO "Define: [incomplete text]" - write proper questions
6. Focus on KEY CONCEPTS, not random sentences

CARD TYPES (in order of difficulty):
1. Definition (BEGINNER): "What was the French Revolution?" → "The French Revolution (1789-1799) was a period of radical social and political upheaval in France..."
2. Timeline (BEGINNER): "When did the Greek war of independence begin?" → "The Greek war of independence began in 1821..."
3. People (INTERMEDIATE): "Who was Giuseppe Mazzini?" → "Giuseppe Mazzini was an Italian revolutionary who founded Young Italy..."
4. Cause-Effect (INTERMEDIATE): "What caused the rise of nationalism in Europe?" → "Nationalism rose due to..."
5. Analysis (ADVANCED): "Why was the Frankfurt Parliament significant?" → "The Frankfurt Parliament was significant because..."

TEXT TO CONVERT:
{text_excerpt}

QUALITY CHECKLIST:
✓ Is the question complete and clear?
✓ Is the answer informative and concise?
✓ Does it focus on important concepts?
✓ Would a student understand this without context?

OUTPUT: Return ONLY valid JSON array with 10-12 HIGH-QUALITY cards:
[
  {{
    "front": "Clear, complete question?",
    "back": "Concise, informative answer (2-4 sentences).",
    "type": "definition | timeline | people | cause-effect | analysis",
    "difficulty": "beginner | intermediate | advanced"
  }}
]""",

    "mathematics": """You are an expert mathematics educator creating flashcards for students.

CRITICAL RULES:
1. Questions must be CLEAR and COMPLETE
2. Include WORKED EXAMPLES with steps
3. Use proper mathematical notation
4. NO incomplete formulas or fragments
5. Each card must be SELF-CONTAINED
6. Focus on UNDERSTANDING, not just memorization

CARD TYPES (in order of difficulty):
1. Definition (BEGINNER): "What is a prime number?" → "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. Examples: 2, 3, 5, 7, 11."
2. Formula (BEGINNER): "What is the formula for HCF and LCM relationship?" → "For any two positive integers a and b: HCF(a,b) × LCM(a,b) = a × b"
3. Concept (INTERMEDIATE): "Why is √2 irrational?" → "Assume √2 = a/b in lowest terms. Then 2b² = a², so a is even. Let a = 2c. Then b² = 2c², so b is even. This contradicts lowest terms. Therefore √2 is irrational."
4. Example (INTERMEDIATE): "Find HCF(96, 404) using prime factorization" → "96 = 2⁵ × 3, 404 = 2² × 101. HCF = 2² = 4 (smallest power of common factors)"
5. Practice (ADVANCED): "Prove that 3 + √5 is irrational" → "Assume 3 + √5 = a/b. Then √5 = (a-3b)/b. Since a,b are integers, √5 would be rational, which contradicts the fact that √5 is irrational."

TEXT TO CONVERT:
{text_excerpt}

QUALITY CHECKLIST:
✓ Is the mathematical concept explained clearly?
✓ Are formulas and notation correct?
✓ Do examples show complete solutions?
✓ Would a student understand the steps?

OUTPUT: Return ONLY valid JSON array with 12-15 HIGH-QUALITY cards:
[
  {{
    "front": "Clear mathematical question?",
    "back": "Complete answer with steps/explanation.",
    "type": "definition | formula | concept | example | practice",
    "difficulty": "beginner | intermediate | advanced"
  }}
]""",

    "science": """You are an expert science educator creating flashcards for students.

CRITICAL RULES:
1. Questions must be CLEAR and SPECIFIC
2. Answers must be SCIENTIFICALLY ACCURATE
3. Include units and measurements
4. NO incomplete sentences or fragments
5. Each card must be SELF-CONTAINED
6. Focus on UNDERSTANDING concepts

CARD TYPES (in order of difficulty):
1. Definition (BEGINNER): "What is photosynthesis?" → "Photosynthesis is the process by which plants use sunlight, water, and carbon dioxide to produce oxygen and glucose. Equation: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂"
2. Fact (BEGINNER): "What is the speed of light?" → "The speed of light in vacuum is approximately 3 × 10⁸ m/s (300,000 km/s)."
3. Process (INTERMEDIATE): "Explain the water cycle" → "The water cycle involves: 1) Evaporation (water → vapor), 2) Condensation (vapor → clouds), 3) Precipitation (rain/snow), 4) Collection (rivers/oceans)."
4. Concept (INTERMEDIATE): "Why do objects fall?" → "Objects fall due to gravity, a force of attraction between masses. On Earth, gravity accelerates objects at 9.8 m/s²."
5. Experiment (ADVANCED): "How to test for starch?" → "Add iodine solution to the sample. If starch is present, the solution turns blue-black. This is because iodine forms a complex with starch molecules."

TEXT TO CONVERT:
{text_excerpt}

QUALITY CHECKLIST:
✓ Is the science accurate and clear?
✓ Are units and measurements included?
✓ Does it explain the concept well?
✓ Would a student understand without prior context?

OUTPUT: Return ONLY valid JSON array with 10-12 HIGH-QUALITY cards:
[
  {{
    "front": "Clear scientific question?",
    "back": "Accurate, complete answer with details.",
    "type": "definition | fact | process | concept | experiment",
    "difficulty": "beginner | intermediate | advanced"
  }}
]""",

    "general": """You are an expert educator creating high-quality flashcards.

CRITICAL RULES:
1. Each card must be COMPLETE and SELF-CONTAINED
2. Questions must be CLEAR and SPECIFIC
3. Answers must be CONCISE but INFORMATIVE (2-4 sentences)
4. NO incomplete sentences or fragments
5. NO "Define: [random text]" - write proper questions
6. Focus on KEY CONCEPTS from the text

CARD TYPES (in order of difficulty):
1. Definition (BEGINNER): "What is [key term]?" → "Clear, concise definition with example."
2. Fact (BEGINNER): "When/Where/Who [specific fact]?" → "Specific factual answer."
3. Concept (INTERMEDIATE): "Explain [concept]" → "Clear explanation of how/why something works."
4. Example (INTERMEDIATE): "Give an example of [concept]" → "Concrete example with explanation."
5. Analysis (ADVANCED): "Why is [concept] important?" → "Analysis of significance and implications."

TEXT TO CONVERT:
{text_excerpt}

QUALITY CHECKLIST:
✓ Is the question complete and clear?
✓ Is the answer informative and concise?
✓ Does it focus on important concepts?
✓ Would someone understand this without reading the source?

OUTPUT: Return ONLY valid JSON array with 10-12 HIGH-QUALITY cards:
[
  {{
    "front": "Clear, complete question?",
    "back": "Concise, informative answer (2-4 sentences).",
    "type": "definition | fact | concept | example | analysis",
    "difficulty": "beginner | intermediate | advanced"
  }}
]"""
}

def get_prompt_for_subject(subject: str) -> str:
    """Get the appropriate prompt template for a subject."""
    return SUBJECT_PROMPTS.get(subject.lower(), SUBJECT_PROMPTS["general"])


def sort_cards_by_difficulty(cards: list[dict]) -> list[dict]:
    """
    Sort cards by difficulty level: beginner → intermediate → advanced.
    Also sorts by type within each difficulty level.
    """
    # Define difficulty order
    difficulty_order = {"beginner": 0, "intermediate": 1, "advanced": 2}
    
    # Define type order for each subject
    type_order = {
        # History
        "definition": 0, "timeline": 1, "people": 2, "cause-effect": 3, "analysis": 4,
        # Math
        "formula": 0, "concept": 2, "example": 3, "practice": 4,
        # Science
        "fact": 1, "process": 2, "experiment": 4,
        # General
        "default": 5
    }
    
    def get_sort_key(card):
        difficulty = card.get("difficulty", "intermediate")
        card_type = card.get("type", "concept")
        
        diff_value = difficulty_order.get(difficulty, 1)
        type_value = type_order.get(card_type, 5)
        
        return (diff_value, type_value)
    
    return sorted(cards, key=get_sort_key)


def generate_cards_from_topics(topics: list[dict], subject: str = "general") -> list[dict]:
    """
    Generate flashcards from organized topics.
    Prioritizes high-importance topics and generates more cards for them.
    
    Args:
        topics: List of dicts with 'topic', 'content', and 'importance' keys
        subject: Subject type (history, mathematics, science, general)
    
    Returns:
        List of flashcard dicts
    """
    all_cards = []
    
    # Sort topics by importance (high -> medium -> low)
    importance_order = {"high": 0, "medium": 1, "low": 2}
    sorted_topics = sorted(topics, key=lambda t: importance_order.get(t.get("importance", "medium"), 1))
    
    for topic_data in sorted_topics:
        topic_name = topic_data.get("topic", "Unknown Topic")
        content = topic_data.get("content", "")
        importance = topic_data.get("importance", "medium")
        
        if not content or len(content.split()) < 20:
            continue
        
        # Generate cards for this topic
        cards = generate_cards_from_text(content, topic_context=topic_name, subject=subject)
        
        # Adjust number of cards based on importance
        if importance == "high":
            max_cards = 15
        elif importance == "medium":
            max_cards = 10
        else:
            max_cards = 6
        
        # Add topic tag to each card
        for card in cards[:max_cards]:
            card["topic"] = topic_name
            all_cards.append(card)
    
    # Sort all cards by difficulty (beginner → intermediate → advanced)
    all_cards = sort_cards_by_difficulty(all_cards)
    
    return all_cards


def generate_cards_from_text(text: str, topic_context: str = None, subject: str = "general") -> list[dict]:
    """
    Generate flashcards from text using Groq API.
    Falls back to rule-based generation only if API key is missing.
    """
    if not GROQ_API_KEY:
        print("⚠ No GROQ_API_KEY found - using rule-based fallback")
        return _generate_rule_based(text, topic_context, subject)

    try:
        cards = _generate_with_groq(text, topic_context, subject)
        if cards:
            return cards
        print("⚠ Groq returned 0 cards - using rule-based fallback")
        return _generate_rule_based(text, topic_context, subject)
    except Exception as e:
        print(f"❌ Groq generation FAILED: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        print("⚠ Falling back to rule-based generation")
        return _generate_rule_based(text, topic_context, subject)


def _generate_with_groq(text: str, topic_context: str = None, subject: str = "general") -> list[dict]:
    """Generate cards using Groq API."""
    from groq import Groq

    print(f"  🤖 Calling Groq API (key: {GROQ_API_KEY[:8]}...) model: llama-3.3-70b-versatile")
    client = Groq(api_key=GROQ_API_KEY)
    
    prompt_template = get_prompt_for_subject(subject)
    text_with_context = f"TOPIC: {topic_context}\n\n{text}" if topic_context else text
    prompt = prompt_template.format(text_excerpt=text_with_context[:3500])

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": f"You are an expert {subject} educator. Generate high-quality flashcards. Return ONLY valid JSON array, no other text."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3,
        max_tokens=3000,
    )

    content = response.choices[0].message.content.strip()
    print(f"  ✅ Groq responded ({len(content)} chars)")
    cards = _parse_cards_json(content)
    print(f"  ✅ Parsed {len(cards)} valid cards from Groq")
    return cards


def _generate_rule_based(text: str, topic_context: str = None, subject: str = "general") -> list[dict]:
    """
    Improved rule-based card generation when no API key is available.
    Extracts key concepts and creates meaningful Q&A pairs.
    
    Args:
        text: Text content
        topic_context: Optional topic name for better card generation
        subject: Subject type for appropriate card generation
    """
    # Split into sentences
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if len(s.strip()) > 30]
    
    if not sentences:
        return []
    
    cards = []
    
    # Extract key terms (capitalized words, numbers, formulas)
    key_terms = set()
    for sentence in sentences:
        # Find capitalized terms (likely important concepts)
        caps = re.findall(r'\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\b', sentence)
        key_terms.update(caps)
        
        # Find numbers with context (dates, measurements)
        numbers = re.findall(r'\b\d+(?:\.\d+)?\s*(?:years?|days?|meters?|km|kg|%|°C)?\b', sentence)
        key_terms.update(numbers)
    
    # Generate definition cards for key terms
    for term in list(key_terms)[:5]:
        # Find sentence containing this term
        for sentence in sentences:
            if term in sentence:
                cards.append({
                    "front": f"What is {term}?",
                    "back": sentence,
                    "type": "definition",
                    "difficulty": "beginner"
                })
                break
    
    # Generate concept cards from important sentences
    important_sentences = [s for s in sentences if len(s.split()) > 15 and len(s.split()) < 50]
    
    for i, sentence in enumerate(important_sentences[:8]):
        # Create different question types based on sentence structure
        if "because" in sentence.lower() or "due to" in sentence.lower():
            # Cause-effect card
            parts = re.split(r'\bbecause\b|\bdue to\b', sentence, flags=re.IGNORECASE)
            if len(parts) == 2:
                cards.append({
                    "front": f"Why {parts[0].strip().lower()}?",
                    "back": f"Because {parts[1].strip()}",
                    "type": "cause-effect" if subject == "history" else "concept",
                    "difficulty": "intermediate"
                })
        elif any(word in sentence.lower() for word in ["formula", "equation", "="]):
            # Formula card
            cards.append({
                "front": f"What is the formula mentioned in: {sentence[:50]}...?",
                "back": sentence,
                "type": "formula",
                "difficulty": "beginner"
            })
        elif re.search(r'\b(is|are|was|were)\b', sentence):
            # Definition/fact card
            match = re.search(r'(.+?)\s+(is|are|was|were)\s+(.+)', sentence)
            if match:
                subject_part = match.group(1).strip()
                predicate = match.group(3).strip()
                cards.append({
                    "front": f"What {match.group(2)} {subject_part}?",
                    "back": predicate,
                    "type": "fact" if subject == "science" else "definition",
                    "difficulty": "beginner"
                })
        else:
            # General concept card
            # Extract first few words as topic
            words = sentence.split()
            topic_words = " ".join(words[:5])
            cards.append({
                "front": f"Explain: {topic_words}...",
                "back": sentence,
                "type": "concept",
                "difficulty": "intermediate"
            })
    
    # Add a summary card
    if len(sentences) >= 3:
        summary = ". ".join(sentences[:3])
        cards.append({
            "front": f"Summarize the main points{f' about {topic_context}' if topic_context else ''}.",
            "back": summary,
            "type": "analysis",
            "difficulty": "advanced"
        })
    
    # Remove duplicates and limit
    seen = set()
    unique_cards = []
    for card in cards:
        key = (card["front"], card["back"])
        if key not in seen:
            seen.add(key)
            unique_cards.append(card)
    
    return unique_cards[:12]


def _parse_cards_json(content: str) -> list[dict]:
    """Parse and validate JSON card output from LLM with strict quality control."""
    content = re.sub(r"^```(?:json)?\s*", "", content, flags=re.MULTILINE)
    content = re.sub(r"\s*```$", "", content, flags=re.MULTILINE)
    content = content.strip()

    try:
        cards = json.loads(content)
    except json.JSONDecodeError:
        match = re.search(r'\[.*\]', content, re.DOTALL)
        if match:
            cards = json.loads(match.group())
        else:
            raise ValueError("Could not parse card JSON from LLM response")

    valid_cards = []
    rejected_count = 0
    
    for card in cards:
        front = card.get("front", "").strip()
        back = card.get("back", "").strip()
        card_type = card.get("type", "concept")
        difficulty = card.get("difficulty", "intermediate")

        # Quality checks
        if len(front) < 10 or len(back) < 15:
            rejected_count += 1
            continue
            
        # Reject incomplete or low-quality cards
        if any(pattern in front.lower() for pattern in [
            "define:", "what is the formula for we", "explain the concept of we",
            "give an example/solved problem for:", "solve this challenge related to"
        ]):
            # Check if it's actually a proper question
            if not front.endswith("?") and "what" not in front.lower() and "how" not in front.lower():
                rejected_count += 1
                continue
        
        # Reject cards with incomplete sentences
        if front.count(" ") < 3 or back.count(" ") < 5:
            rejected_count += 1
            continue
            
        # Reject cards that are just fragments
        if not any(char in front for char in "?!.") and len(front.split()) < 5:
            rejected_count += 1
            continue
        
        # Truncate if too long
        if len(front) > 500:
            front = front[:500]
        if len(back) > 800:
            back = back[:800]

        # Validate card type
        valid_types = ["definition", "concept", "example", "formula", "practice", "timeline", 
                      "people", "cause-effect", "analysis", "fact", "process", "experiment"]
        if card_type not in valid_types:
            card_type = "concept"
        
        # Validate difficulty
        if difficulty not in ["beginner", "intermediate", "advanced"]:
            difficulty = "intermediate"

        valid_cards.append({
            "front": front, 
            "back": back, 
            "type": card_type,
            "difficulty": difficulty
        })
    
    if rejected_count > 0:
        print(f"  ⚠ Rejected {rejected_count} low-quality cards")

    return valid_cards
