import json
import re
from config import GROQ_API_KEY, PAGEINDEX_API_KEY
from typing import Optional


def generate_cards_with_pageindex(json_path: str, subject: str = "general") -> list[dict]:
    """
    Generate flashcards using the structure generated by the LOCAL PageIndex clone.
    Traverses the JSON tree to generate cards for each significant node.
    """
    import json
    with open(json_path, "r", encoding="utf-8") as f:
        structure = json.load(f)

    # Helper function to get text from all nodes in the tree
    def extract_node_texts(nodes, result_list):
        if isinstance(nodes, list):
            for node in nodes:
                extract_node_texts(node, result_list)
        elif isinstance(nodes, dict):
            # Only use nodes with substantial text
            text = nodes.get("text", "")
            if len(text.split()) > 100:
                result_list.append(text)
            
            if "nodes" in nodes:
                extract_node_texts(nodes["nodes"], result_list)

    all_texts = []
    extract_node_texts(structure, all_texts)

    # If the tree is empty or too small, fall back to extracting text from the file (handled in route)
    if not all_texts:
        return []

    # Generate cards for each extracted text block
    all_cards = []
    # Limit to top 10 sections to avoid huge costs/time unless it's a massive doc
    for text in all_texts[:10]:
        cards = generate_cards_from_text(text, subject=subject)
        all_cards.extend(cards)

    return all_cards

SUBJECT_PROMPTS = {
    "history": """You are an expert history educator creating flashcards for CBSE Class 10 students.

CARD TYPES (in order of difficulty - BEGINNER to ADVANCED):
1. Definition (BEGINNER): Basic terms and concepts (e.g., "What was the French Revolution?")
2. Timeline (BEGINNER): Important dates and events (e.g., "When did the Greek war of independence begin?")
3. People (INTERMEDIATE): Key figures and their contributions (e.g., "Who was Giuseppe Mazzini?")
4. Cause-Effect (INTERMEDIATE): Why events happened (e.g., "What caused the rise of nationalism?")
5. Analysis (ADVANCED): Understanding significance and impact (e.g., "Why was the Frankfurt Parliament significant?")

REQUIREMENTS:
- Front: Clear, specific question
- Back: Concise answer (2-4 sentences max)
- Use simple language for Class 10 level
- Focus on CBSE exam-relevant content
- Include dates, names, and key facts
- Generate cards in PROGRESSIVE ORDER: Start with definitions, then timeline, then people, then cause-effect, then analysis
- Generate 10-12 cards per text chunk with this progression

TEXT TO CONVERT:
{text_excerpt}

OUTPUT: Return ONLY valid JSON array IN ORDER (beginner to advanced):
[
  {{
    "front": "Clear question here?",
    "back": "Concise answer here.",
    "type": "definition | timeline | people | cause-effect | analysis",
    "difficulty": "beginner | intermediate | advanced"
  }}
]

Generate 10-12 cards in PROGRESSIVE difficulty order.""",

    "mathematics": """You are an expert mathematics educator creating flashcards.

CARD TYPES (in order of difficulty - BEGINNER to ADVANCED):
1. Definition (BEGINNER): Basic terms (e.g., "What is a quadratic equation?")
2. Formula (BEGINNER): Key equations (e.g., "What is the quadratic formula?")
3. Concept (INTERMEDIATE): Understanding principles (e.g., "Why must a ≠ 0?")
4. Example (INTERMEDIATE): Solved problems (e.g., "Solve: x² - 5x + 6 = 0")
5. Practice (ADVANCED): Complex problems (e.g., "Find roots of x² - 9 = 0 and explain")

REQUIREMENTS:
- Front: One clear question
- Back: Step-by-step solution or clear explanation
- Use proper mathematical notation
- Include worked examples
- Progress from basic definitions to complex problems
- Generate 10-15 cards in PROGRESSIVE ORDER

TEXT TO CONVERT:
{text_excerpt}

OUTPUT: Return ONLY valid JSON array IN ORDER (beginner to advanced):
[
  {{
    "front": "Question?",
    "back": "Answer with steps if needed.",
    "type": "definition | formula | concept | example | practice",
    "difficulty": "beginner | intermediate | advanced"
  }}
]

Generate 10-15 cards in PROGRESSIVE difficulty order.""",

    "science": """You are an expert science educator creating flashcards.

CARD TYPES (in order of difficulty - BEGINNER to ADVANCED):
1. Definition (BEGINNER): Basic scientific terms (e.g., "What is photosynthesis?")
2. Fact (BEGINNER): Important information (e.g., "What is the speed of light?")
3. Process (INTERMEDIATE): How things work (e.g., "Explain the water cycle")
4. Concept (INTERMEDIATE): Understanding principles (e.g., "Why do objects fall?")
5. Experiment (ADVANCED): Practical applications (e.g., "How to test for starch?")

REQUIREMENTS:
- Front: Clear, specific question
- Back: Accurate scientific answer (2-4 sentences)
- Use diagrams descriptions when helpful
- Include units and measurements
- Focus on understanding, not memorization
- Progress from basic facts to complex concepts
- Generate 10-12 cards in PROGRESSIVE ORDER

TEXT TO CONVERT:
{text_excerpt}

OUTPUT: Return ONLY valid JSON array IN ORDER (beginner to advanced):
[
  {{
    "front": "Question?",
    "back": "Scientific answer.",
    "type": "definition | fact | process | concept | experiment",
    "difficulty": "beginner | intermediate | advanced"
  }}
]

Generate 10-12 cards in PROGRESSIVE difficulty order.""",

    "general": """You are an expert educator creating flashcards.

CARD TYPES (in order of difficulty - BEGINNER to ADVANCED):
1. Definition (BEGINNER): Key terms and concepts
2. Fact (BEGINNER): Important information
3. Concept (INTERMEDIATE): Understanding and reasoning
4. Example (INTERMEDIATE): Practical applications
5. Analysis (ADVANCED): Critical thinking

REQUIREMENTS:
- Front: One clear question
- Back: Concise, accurate answer (2-4 sentences)
- Self-contained cards
- Age-appropriate language
- Focus on understanding
- Progress from basic to advanced
- Generate 10-12 cards in PROGRESSIVE ORDER

TEXT TO CONVERT:
{text_excerpt}

OUTPUT: Return ONLY valid JSON array IN ORDER (beginner to advanced):
[
  {{
    "front": "Question?",
    "back": "Answer.",
    "type": "definition | fact | concept | example | analysis",
    "difficulty": "beginner | intermediate | advanced"
  }}
]

Generate 10-12 cards in PROGRESSIVE difficulty order."""
}

def get_prompt_for_subject(subject: str) -> str:
    """Get the appropriate prompt template for a subject."""
    return SUBJECT_PROMPTS.get(subject.lower(), SUBJECT_PROMPTS["general"])


def sort_cards_by_difficulty(cards: list[dict]) -> list[dict]:
    """
    Sort cards by difficulty level: beginner → intermediate → advanced.
    Also sorts by type within each difficulty level.
    """
    # Define difficulty order
    difficulty_order = {"beginner": 0, "intermediate": 1, "advanced": 2}
    
    # Define type order for each subject
    type_order = {
        # History
        "definition": 0, "timeline": 1, "people": 2, "cause-effect": 3, "analysis": 4,
        # Math
        "formula": 0, "concept": 2, "example": 3, "practice": 4,
        # Science
        "fact": 1, "process": 2, "experiment": 4,
        # General
        "default": 5
    }
    
    def get_sort_key(card):
        difficulty = card.get("difficulty", "intermediate")
        card_type = card.get("type", "concept")
        
        diff_value = difficulty_order.get(difficulty, 1)
        type_value = type_order.get(card_type, 5)
        
        return (diff_value, type_value)
    
    return sorted(cards, key=get_sort_key)


def generate_cards_from_topics(topics: list[dict], subject: str = "general") -> list[dict]:
    """
    Generate flashcards from organized topics.
    Prioritizes high-importance topics and generates more cards for them.
    
    Args:
        topics: List of dicts with 'topic', 'content', and 'importance' keys
        subject: Subject type (history, mathematics, science, general)
    
    Returns:
        List of flashcard dicts
    """
    all_cards = []
    
    # Sort topics by importance (high -> medium -> low)
    importance_order = {"high": 0, "medium": 1, "low": 2}
    sorted_topics = sorted(topics, key=lambda t: importance_order.get(t.get("importance", "medium"), 1))
    
    for topic_data in sorted_topics:
        topic_name = topic_data.get("topic", "Unknown Topic")
        content = topic_data.get("content", "")
        importance = topic_data.get("importance", "medium")
        
        if not content or len(content.split()) < 20:
            continue
        
        # Generate cards for this topic
        cards = generate_cards_from_text(content, topic_context=topic_name, subject=subject)
        
        # Adjust number of cards based on importance
        if importance == "high":
            max_cards = 15
        elif importance == "medium":
            max_cards = 10
        else:
            max_cards = 6
        
        # Add topic tag to each card
        for card in cards[:max_cards]:
            card["topic"] = topic_name
            all_cards.append(card)
    
    # Sort all cards by difficulty (beginner → intermediate → advanced)
    all_cards = sort_cards_by_difficulty(all_cards)
    
    return all_cards


def generate_cards_from_text(text: str, topic_context: str = None, subject: str = "general") -> list[dict]:
    """
    Generate flashcards from text using Groq API.
    Falls back to rule-based generation if API key is not configured.
    
    Args:
        text: Text content to generate cards from
        topic_context: Optional topic name for context
        subject: Subject type for appropriate prompt selection
    """
    if GROQ_API_KEY:
        try:
            return _generate_with_groq(text, topic_context, subject)
        except Exception as e:
            print(f"Groq generation failed: {e}, falling back to rule-based")

    return _generate_rule_based(text, topic_context, subject)


def _generate_with_groq(text: str, topic_context: str = None, subject: str = "general") -> list[dict]:
    """Generate cards using Groq API (OpenAI-compatible)."""
    from groq import Groq

    client = Groq(api_key=GROQ_API_KEY)
    
    # Get subject-specific prompt
    prompt_template = get_prompt_for_subject(subject)
    
    # Add topic context to text if available
    text_with_context = f"TOPIC: {topic_context}\n\n{text}" if topic_context else text
    
    # Format the prompt
    prompt = prompt_template.format(text_excerpt=text_with_context[:3500])

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": f"You are an expert {subject} educator. Generate high-quality flashcards. Return only valid JSON."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3,
        max_tokens=2500,
    )

    content = response.choices[0].message.content.strip()
    return _parse_cards_json(content)


def _generate_rule_based(text: str, topic_context: str = None, subject: str = "general") -> list[dict]:
    """
    Smart rule-based card generation when no API key is available.
    Extracts key sentences and creates Q&A pairs.
    
    Args:
        text: Text content
        topic_context: Optional topic name for better card generation
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if len(s.strip()) > 20]
    cards = []

    if not sentences:
        cards.append({
            "front": f"Summarize the key concepts{f' about {topic_context}' if topic_context else ''}.",
            "back": text[:300].strip() + "..." if len(text) > 300 else text.strip(),
            "type": "concept"
        })
        return cards

    card_templates = [
        ("definition", "beginner", "Define: {topic}", "{detail}"),
        ("formula", "beginner", "What is the formula for {topic}?", "{detail}"),
        ("concept", "intermediate", "Explain the concept of {topic}.", "{detail}"),
        ("example", "intermediate", "Give an example/solved problem for: {topic}", "{detail}"),
        ("practice", "advanced", "Solve this challenge related to {topic}", "Answer: {detail}"),
    ]

    for i, sentence in enumerate(sentences[:12]):
        words = sentence.split()
        if len(words) < 4:
            continue

        # Use topic context if available, otherwise extract from sentence
        if topic_context:
            topic = topic_context
        else:
            topic = " ".join(words[:min(6, len(words))])
            
        template_idx = i % len(card_templates)
        card_type, difficulty, front_tmpl, back_tmpl = card_templates[template_idx]

        # Format both front and back with available data
        front = front_tmpl.format(topic=topic)
        back = back_tmpl.format(detail=sentence)

        cards.append({
            "front": front,
            "back": back,
            "type": card_type,
            "difficulty": difficulty
        })

    summary_text = ". ".join(sentences[:3])
    cards.append({
        "front": f"What are the main topics covered{f' in {topic_context}' if topic_context else ''}?",
        "back": summary_text[:400],
        "type": "concept",
        "difficulty": "intermediate"
    })

    return cards[:12]


def _parse_cards_json(content: str) -> list[dict]:
    """Parse and validate JSON card output from LLM."""
    content = re.sub(r"^```(?:json)?\s*", "", content, flags=re.MULTILINE)
    content = re.sub(r"\s*```$", "", content, flags=re.MULTILINE)
    content = content.strip()

    try:
        cards = json.loads(content)
    except json.JSONDecodeError:
        match = re.search(r'\[.*\]', content, re.DOTALL)
        if match:
            cards = json.loads(match.group())
        else:
            raise ValueError("Could not parse card JSON from LLM response")

    valid_cards = []
    for card in cards:
        front = card.get("front", "").strip()
        back = card.get("back", "").strip()
        card_type = card.get("type", "concept")
        difficulty = card.get("difficulty", "intermediate")

        if len(front) < 10 or len(back) < 10:
            continue
        if len(front) > 500 or len(back) > 500:
            front = front[:500]
            back = back[:500]

        # Validate card type
        valid_types = ["definition", "concept", "example", "formula", "practice", "timeline", 
                      "people", "cause-effect", "analysis", "fact", "process", "experiment", "edge_case", "application"]
        if card_type not in valid_types:
            card_type = "concept"
        
        # Validate difficulty
        if difficulty not in ["beginner", "intermediate", "advanced"]:
            difficulty = "intermediate"

        valid_cards.append({
            "front": front, 
            "back": back, 
            "type": card_type,
            "difficulty": difficulty
        })

    return valid_cards
