services:
  - type: web
    name: flashcard-engine-api-embz
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://flashcard-engine-lac.vercel.app
      - key: JWT_SECRET
        value: flashcard-engine-super-secret-jwt-key-2026
